FROM flink:2.2.0-scala_2.12-java17

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends python3 python3-pip python3-dev build-essential && \
    python3 -m pip install --no-cache-dir --upgrade pip setuptools wheel && \
    python3 -m pip install --no-cache-dir apache-flink==2.2.0 fastavro pandas pyyaml && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

COPY src/ src/
COPY data/ data/

ENV PYTHONPATH=/workspace

USER flink
